<?php


namespace Controller;

class ProfileuserController extends DisplayController
{
    protected $user_data;
    public function profile () {
            //Запускам класс постредник для проверки авторизован ли пользователь
            $this->middle->isUserLogin($this->lang_prefix);
                return $this->display();
        }

        protected function display()
        {   
            $this->user_data = $this->user->getUserData($_SESSION['user_id']);
            $this->mainbar = $this->mainBar();
            parent::display(); // TODO: Change the autogenerated stub
        }

        protected function mainBar () {
            $data = $this->view->render('profile.php',
                [
                    'user' => $this->user_data
                ]);
        return $data;
    }
}