<?php


namespace Controller;


class ProfileuserController extends DisplayController
{
        public function execute () {
            return $this->display();
            parent::display();
        }

        protected function display()
        {
            $this->title .= 'USER';
            $this->user = $this->getData(2);
            $this->mainbar = $this->mainBar();
            parent::display(); // TODO: Change the autogenerated stub
        }

        public function getData ($id) {
            return $this->model->getData($id);
        }

        protected function mainBar () {
        $data = $this->view->render('profile.php',
            [
                'user'  => $this->user
            ]);
        return $data;
    }
}